/**
 * Algerian Wilayas - 69 Wilayas en français
 * Les communes sont saisies manuellement par l'utilisateur
 */

export interface Wilaya {
    id: string;
    name: string;
    arabicName: string;
    communes?: string[];
}

export const ALGERIA_LOCATIONS: Wilaya[] = [
    { id: "01", name: "Adrar", arabicName: "أدرار" },
    { id: "02", name: "Chlef", arabicName: "الشلف" },
    { id: "03", name: "Laghouat", arabicName: "الأغواط" },
    { id: "04", name: "Oum El Bouaghi", arabicName: "أم البواقي" },
    { id: "05", name: "Batna", arabicName: "باتنة" },
    { id: "06", name: "Béjaïa", arabicName: "بجاية" },
    { id: "07", name: "Biskra", arabicName: "بسكرة" },
    { id: "08", name: "Béchar", arabicName: "بشار" },
    { id: "09", name: "Blida", arabicName: "البليدة" },
    { id: "10", name: "Bouira", arabicName: "البويرة" },
    { id: "11", name: "Tamanrasset", arabicName: "تمنراست" },
    { id: "12", name: "Tébessa", arabicName: "تبسة" },
    { id: "13", name: "Tlemcen", arabicName: "تلمسان" },
    { id: "14", name: "Tiaret", arabicName: "تيارت" },
    { id: "15", name: "Tizi Ouzou", arabicName: "تيزي وزو" },
    { id: "16", name: "Alger", arabicName: "الجزائر" },
    { id: "17", name: "Djelfa", arabicName: "الجلفة" },
    { id: "18", name: "Jijel", arabicName: "جيجل" },
    { id: "19", name: "Sétif", arabicName: "سطيف" },
    { id: "20", name: "Saïda", arabicName: "سعيدة" },
    { id: "21", name: "Skikda", arabicName: "سكيكدة" },
    { id: "22", name: "Sidi Bel Abbès", arabicName: "سيدي بلعباس" },
    { id: "23", name: "Annaba", arabicName: "عنابة" },
    { id: "24", name: "Guelma", arabicName: "قالمة" },
    { id: "25", name: "Constantine", arabicName: "قسنطينة" },
    { id: "26", name: "Médéa", arabicName: "المدية" },
    { id: "27", name: "Mostaganem", arabicName: "مستغانم" },
    { id: "28", name: "M'Sila", arabicName: "المسيلة" },
    { id: "29", name: "Mascara", arabicName: "معسكر" },
    { id: "30", name: "Ouargla", arabicName: "ورقلة" },
    { id: "31", name: "Oran", arabicName: "وهران" },
    { id: "32", name: "El Bayadh", arabicName: "البيض" },
    { id: "33", name: "Illizi", arabicName: "إليزي" },
    { id: "34", name: "Bordj Bou Arréridj", arabicName: "برج بوعريريج" },
    { id: "35", name: "Boumerdès", arabicName: "بومرداس" },
    { id: "36", name: "El Tarf", arabicName: "الطارف" },
    { id: "37", name: "Tindouf", arabicName: "تندوف" },
    { id: "38", name: "Tissemsilt", arabicName: "تيسمسيلت" },
    { id: "39", name: "El Oued", arabicName: "الوادي" },
    { id: "40", name: "Khenchela", arabicName: "خنشلة" },
    { id: "41", name: "Souk Ahras", arabicName: "سوق أهراس" },
    { id: "42", name: "Tipaza", arabicName: "تيبازة" },
    { id: "43", name: "Mila", arabicName: "ميلة" },
    { id: "44", name: "Aïn Defla", arabicName: "عين الدفلى" },
    { id: "45", name: "Naâma", arabicName: "النعامة" },
    { id: "46", name: "Aïn Témouchent", arabicName: "عين تموشنت" },
    { id: "47", name: "Ghardaïa", arabicName: "غرداية" },
    { id: "48", name: "Relizane", arabicName: "غليزان" },
    { id: "49", name: "El M'Ghair", arabicName: "المغير" },
    { id: "50", name: "El Meniaa", arabicName: "المنيعة" },
    { id: "51", name: "Ouled Djellal", arabicName: "أولاد جلال" },
    { id: "52", name: "Bordj Baji Mokhtar", arabicName: "برج باجي مختار" },
    { id: "53", name: "Béni Abbès", arabicName: "بني عباس" },
    { id: "54", name: "Timimoun", arabicName: "تيميمون" },
    { id: "55", name: "Touggourt", arabicName: "تقرت" },
    { id: "56", name: "Djanet", arabicName: "جانت" },
    { id: "57", name: "In Salah", arabicName: "عين صالح" },
    { id: "58", name: "In Guezzam", arabicName: "عين قزام" },
    { id: "59", name: "Aflou", arabicName: "أفلوا" },
    { id: "60", name: "Barika", arabicName: "بريكة" },
    { id: "61", name: "Ksar Chellala", arabicName: "قصر الشلالة" },
    { id: "62", name: "Messaad", arabicName: "مسعد" },
    { id: "63", name: "Aïn Oussara", arabicName: "عين وسارة" },
    { id: "64", name: "Boussaâda", arabicName: "بوسعادة" },
    { id: "65", name: "El Abiodh Sidi Cheikh", arabicName: "الأبيض سيدي الشيخ" },
    { id: "66", name: "El Kantara", arabicName: "القنطرة" },
    { id: "67", name: "Bir El Ater", arabicName: "بئر العاتر" },
    { id: "68", name: "Ksar El Boukhari", arabicName: "قصر البخاري" },
    { id: "69", name: "El Aricha", arabicName: "العريشة" },
];
